### ISSUE TITLE
compile file on OSX platform

### ISSUE THREAD

**Issue by xin-xinhanggao** [cheind/poisson-image-editing#1]
Hello!
While compile file on OSX platform, like this

[ 10%] Building CXX object CMakeFiles/blend.dir/src/poisson_solver.cpp.o
[ 20%] Building CXX object CMakeFiles/blend.dir/src/clone.cpp.o
[ 30%] Building CXX object CMakeFiles/blend.dir/src/blend.cpp.o
[ 40%] Linking CXX static library libblend.a
[ 40%] Built target blend
Scanning dependencies of target seamless_blending
[ 50%] Building CXX object CMakeFiles/seamless_blending.dir/examples/seamless_blending.cpp.o
[ 60%] Linking CXX executable seamless_blending
[ 60%] Built target seamless_blending
Scanning dependencies of target seamless_cloning
[ 70%] Building CXX object CMakeFiles/seamless_cloning.dir/examples/seamless_cloning.cpp.o
[ 80%] Linking CXX executable seamless_cloning
[ 80%] Built target seamless_cloning
Scanning dependencies of target tests
[ 90%] Building CXX object CMakeFiles/tests.dir/tests/poisson.cpp.o
[100%] Linking CXX executable tests
ld: can't open output file for writing: tests, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [tests] Error 1
make[1]: **\* [CMakeFiles/tests.dir/all] Error 2
make: **\* [all] Error 2

Would you please tell me which step is wrong?

**Comment by cheind** [comment]
Hi,

will have a look at it, but this line

`ld: can't open output file for writing: tests, errno=21 for architecture x86_64`

rings a bell. Are you sure that the tests executable file is writable? It seems like the other examples compile fine.

**Comment by xin-xinhanggao** [comment]
Thanks for your reply, I am a new comer to opencv. Maybe the step to install opencv is wrong, i will uninstall opencv and try again.
