### ISSUE TITLE
Something error about naive result

### ISSUE THREAD

**Issue by xin-xinhanggao** [cheind/poisson-image-editing#3]
![naive](https://cloud.githubusercontent.com/assets/20569510/20254800/ac8e5e70-aa72-11e6-830d-4dbd2383ef72.png)

In the center of the follow image is something discordant.
![error](https://cloud.githubusercontent.com/assets/20569510/20254840/f9930e3c-aa72-11e6-9e76-aa6855d7d20d.png)
Is there something wrong in naive copy?

**Comment by cheind** [comment]
Hi,

I don't think so, only the copy stencil's mask ist not 255 everywhere...

HanggaoXin notifications@github.com schrieb am Mo., 14. Nov. 2016 um
07:02 Uhr:

**Comment by xin-xinhanggao** [comment]
But If I transform the original image to CV_32F, I will get the image like this. So I think maybe there is something wrong with type.
![default](https://cloud.githubusercontent.com/assets/20569510/20272354/8f31db62-aac8-11e6-9cbc-e16b737a0847.png)

**Comment by cheind** [comment]
You are referring to the noise in the naive copy, which is visible around the borders? That is due to the application I used to generate the copy mask. The brush wasn't a fully opaque one, but contained noise. That's why some copy pixels look a bit noisy.

**Comment by xin-xinhanggao** [comment]
Ok, Thank you!
