### ISSUE TITLE
i cant find eigen headers 

### ISSUE THREAD

**Issue by ronyuzhang** [cheind/poisson-image-editing#4]

**Comment by sanggehouzhihoujue** [comment]
@ronyuzhang  eigen is a lib like opencv, so you must download it from the internet

**Comment by cheind** [comment]
get it from [here](http://eigen.tuxfamily.org/index.php?title=Main_Page). You can then set `EIGEN_INCLUDE_DIR` in CMake to point to correct include directory and everything should work out fine. Closing now, reopen if problem persists. 

@sanggehouzhihoujue  thanks for your response!
