### ISSUE TITLE
ubuntu16.04+opencv3.4.1+cmake

### ISSUE THREAD

**Issue by wangyarui** [cheind/poisson-image-editing#5]
richal@wang:~/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found suitable exact version "8.0") 
-- Found OpenCV: /usr/local (found version "3.4.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/build

richal@wang:~/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/build$ makeScanning dependencies of target blend
[ 10%] Building CXX object CMakeFiles/blend.dir/src/poisson_solver.cpp.o
[ 20%] Building CXX object CMakeFiles/blend.dir/src/clone.cpp.o
[ 30%] Building CXX object CMakeFiles/blend.dir/src/blend.cpp.o
[ 40%] Linking CXX static library libblend.a
[ 40%] Built target blend
Scanning dependencies of target seamless_cloning
[ 50%] Building CXX object CMakeFiles/seamless_cloning.dir/examples/seamless_cloning.cpp.o
[ 60%] Linking CXX executable seamless_cloning
[ 60%] Built target seamless_cloning
Scanning dependencies of target seamless_blending
[ 70%] Building CXX object CMakeFiles/seamless_blending.dir/examples/seamless_blending.cpp.o
[ 80%] Linking CXX executable seamless_blending
[ 80%] Built target seamless_blending
Scanning dependencies of target tests
[ 90%] Building CXX object CMakeFiles/tests.dir/tests/poisson.cpp.o
In file included from /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/poisson.cpp:21:0:
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:875:17: error: ‘nullptr_t’ in namespace ‘std’ does not name a type
     inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                 ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:58: error: ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare’ conflicts with a previous declaration
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                          ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:990:44: note: previous declaration ‘namespace Catch::Internal { }::compare’
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:53: error: ‘nullptr_t’ is not a member of ‘std’
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                     ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:70: error: expected primary-expression before ‘*’ token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                      ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:72: error: ‘rhs’ was not declared in this scope
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                        ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:76: error: expression list treated as compound expression in initializer [-fpermissive]
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                            ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:996:78: error: expected ‘;’ before ‘{’ token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                              ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:999:66: error: ‘std::nullptr_t’ has not been declared
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                                  ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:999:44: error: redefinition of ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)’
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                            ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:990:44: note: ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)’ previously declared here
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
In file included from /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/poisson.cpp:21:0:
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:1099:38: error: ‘std::__cxx11::string Catch::toString’ redeclared as different kind of symbol
 std::string toString( std::nullptr_t );
                                      ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:1096:13: note: previous declaration ‘std::__cxx11::string Catch::toString(unsigned char)’
 std::string toString( unsigned char value );
             ^
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:1099:23: error: ‘nullptr_t’ is not a member of ‘std’
 std::string toString( std::nullptr_t );
                       ^
In file included from /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/poisson.cpp:21:0:
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:7351:38: error: ‘std::__cxx11::string Catch::toString’ redeclared as different kind of symbol
 std::string toString( std::nullptr_t ) {
                                      ^
In file included from /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/poisson.cpp:21:0:
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:1222:13: note: previous declaration ‘template<class T, class Allocator> std::__cxx11::string Catch::toString(const std::vector<_Tp, _Alloc>&)’
 std::string toString( std::vector<T,Allocator> const& v ) {
             ^
In file included from /home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/poisson.cpp:21:0:
/home/richal/桌面/2018年4月/图像填充/算法验证/poisson-image-editing/tests/catch.hpp:7351:23: error: ‘nullptr_t’ is not a member of ‘std’
 std::string toString( std::nullptr_t ) {
                       ^
CMakeFiles/tests.dir/build.make:62: recipe for target 'CMakeFiles/tests.dir/tests/poisson.cpp.o' failed
make[2]: *** [CMakeFiles/tests.dir/tests/poisson.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/tests.dir/all' failed
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks a lot...

**Comment by cheind** [comment]
Does this help?

https://stackoverflow.com/questions/24458099/no-type-named-nullptr-t-in-namespace-std

**Comment by DreamChaserMXF** [comment]
I've met the same problem on ubuntu 16.04.4 LTS with GCC5.4.0.
I solved it by adding a line to explicitly active C++11 feature in CMakeList.txt.
Just adding `set (CMAKE_CXX_STANDARD 11)` before defining any target, then everything will play.

**Comment by cheind** [comment]
Thanks for noting!

MengXiangfei <notifications@github.com> schrieb am Mi., 30. Mai 2018 um
08:56 Uhr:

**Comment by wangyarui** [comment]
@cheind  It works well， thanks very much
