### ISSUE TITLE
Fix Bug with Renaming

### ISSUE THREAD

**Issue by 42x00** [cheind/poisson-image-editing#6]
One of the output executables is called 'test', which shares the name with src directory './test' and leads to the failure in 'make'. Better renaming the directory 0v0

**Comment by cheind** [comment]
is test executable placed in same directory as `./test` ? this usually only happens for in source-dir builds.

**Comment by 42x00** [comment]
> is test executable placed in same directory as `./test` ? this usually only happens for in source-dir builds.

Yes. I called 'make' in directory 'poisson-image-editing' and then the three executables were placed in the same directory, which caused the conflict. So I renamed './test' to be './test_src' followed by cmake and make finally fix the problem.

**Comment by cheind** [comment]
I see. I don't have currently time to fix this. Happy to accept a PR though.
